### ISSUE TITLE
Add ARM builds

### ISSUE THREAD

**Issue by ChipWolf** [whatdaybob/sonarr_youtubedl#13]
Versioned tags would be awesome too :)

**Comment by whatdaybob** [comment]
Thanks @ChipWolf. Can you validate it works as expected. I only have x86 available for testing.

**Comment by whatdaybob** [comment]
Container is running the below ytdl

youtube_dl==2021.2.10

Need to verify a newer release doesn't break anything.

**Comment by whatdaybob** [comment]
Arm support added previously
