### ISSUE TITLE
Line 316: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by jaredcat** [whatdaybob/sonarr_youtubedl#16]
Getting an error that's crashing the container:
`TypeError: argument of type 'NoneType' is not iterable` on 
https://github.com/whatdaybob/sonarr_youtubedl/blob/65ec7c3468b5817e550b9966031dc7ee2f54e4d8/app/sonarr_youtubedl.py#L316

Before that
```
[youtube:tab] PL7C128DC8047D1C82: Downloading webpage
[download] Downloading playlist: Rooster Teeth Animated Adventures: Mondays
[youtube:tab] Downloading page 1
ERROR: Unable to download JSON metadata: HTTP Error 410: Gone (caused by <HTTPError 410: 'Gone'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

Similar to https://github.com/whatdaybob/sonarr_youtubedl/issues/15
But this is not ARM. I'm running the container in 64-bit Ubuntu.

**Comment by ArttuH5N1** [comment]
I went into the docker with `docker exec -it sonarr_youtubedl bash` and updated the youtube-dl with `pip install --upgrade youtube-dl` to check if it was just an issue with youtube-dl version and it works now. So the youtube-dl inside the docker just needs to be updated. Should be an easy fix.

**Comment by jaredcat** [comment]
To follow up with my solution for docker compose
I changed the container in the compose file
```
sonarr_youtubedl:
#    image: whatdaybob/sonarr_youtubedl
    build: ./sonarr_youtubedl
    container_name: sonarr_youtubedl
    command: [ "python", "-u", "/app/sonarr_youtubedl.py" ]
.
.
.
```

and created a new Dockerfile inside of `sonarr_youtubedl` dir i had my config stored in
```
FROM whatdaybob/sonarr_youtubedl
RUN pip3 install --upgrade youtube_dl schedule

CMD []
```

Benefit of this is that every restart updates youtube_dl now!
