### ISSUE TITLE
remove black and flake8 from the requirements

### ISSUE THREAD

**Issue by eyadsibai** [whatdaybob/sonarr_youtubedl#17]
https://github.com/whatdaybob/sonarr_youtubedl/blob/65ec7c3468b5817e550b9966031dc7ee2f54e4d8/requirements.txt#L6

I don't think black and flake8 need to be in the requirements.txt ... no needed to run

**Comment by whatdaybob** [comment]
You are probably right as I switched linters early in the build, I was going to use one of them ultimately but was undecided, I will remove both soon and rebuild.

**Comment by eyadsibai** [comment]
you can use linters but not necessary they have to be part of the requirements.txt ... the less in the docker image the better :)

**Comment by whatdaybob** [comment]
Removed in previous commit
