### ISSUE TITLE
Support for other youtubeDL's

### ISSUE THREAD

**Issue by Glynax** [whatdaybob/sonarr_youtubedl#28]
This project desperately needs support for youtubeDLC or DLP. The original project downloads ridiculously slow and even though they update it sometimes now it isn't anywhere near as good as the others. You wouldn't even have to change any of the commands just the binary file that is called.

**Comment by Yankees4life** [comment]
Yep. Yt-dlp is quicker than youtube-dl. I hope the developer considers switching out

**Comment by whatdaybob** [comment]
moved to yt-dlp as requested, tested and pushing to main shortly. Changes are in the dev channel and dev docker container.
