### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Glynax** [whatdaybob/sonarr_youtubedl#30]
I'm getting this error somewhat randomly but always at some point during the run. All my series in the config file are identical except the URL. Even with debug on I'm not really sure what's causing this one. Running on the dev build as of 4/11/2022 with docker-compose. It does add shows up until it dies on this though.
![image](https://user-images.githubusercontent.com/7043861/162871121-b240bf4d-9417-4397-bd12-7034fcfcbf71.png)
![image](https://user-images.githubusercontent.com/7043861/162871279-ffaa0733-3b47-4fd8-8876-6f454f00feba.png)

**Comment by whatdaybob** [comment]
Hi @Glynax, seems like I introduced a silly bug there. I have pushed a fix to dev, it will be in the dev docker builds shortly

**Comment by Glynax** [comment]
Appreciate the quick response. Wasn't sure if I was hitting a bug or something of my own making.
