### ISSUE TITLE
Downloading from crunchyroll

### ISSUE THREAD

**Issue by Ethrel** [whatdaybob/sonarr_youtubedl#43]
Using the dev branch (for yt-dlp, because it's updated to the new crunchyroll frontend), I tried using this image to download video from CrunchyRoll.com

It seems to fail somewhere with no errors shown.

If I turn on the debug mode, I get the output lines from https://github.com/whatdaybob/sonarr_youtubedl/blob/570d76d03e2a56f40f0394438ad9cb66b5c26835/app/sonarr_youtubedl.py#L546-L547 but not anything from inside the try block directly below that. It also does not output the log line from the catch block. I'm not sure what's happening there, but it seems to be failing silently in the try block.

Log file for Demon Slayer attempt from crunchyroll is attached.
[_sonarr_youtubedl_logs.txt](https://github.com/whatdaybob/sonarr_youtubedl/files/10262935/_sonarr_youtubedl_logs.4.txt)

EDIT: I do understand that this project's focus is from youtube, and for that it works wonderfully. However, if it can also handle crunchyroll, I'd be ecstatic. Short of ripping apart the docker container and the script within, I'm not sure how to see what's even going wrong here and how hard a fix it might be.

**Comment by Yankees4life** [comment]
This tool should work for other sites too. Do you got the configuration file on hand? Maybe it's a regex issue. Doesn't look like it found the titles

**Comment by Ethrel** [comment]
I am no longer attempting to use this for crunchyroll, and it seems to work just fine with all the youtube stuff. As such, I'm going to close this issue.
